name: Build and Test

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get dependencies
      run: |
        sudo apt update
        sudo apt install make systemd-container -y

    - name: Build
      run: make

    - name: Test
      run: make test --always-make

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: nomad-driver-nspawn
        path: nomad-driver-nspawn
